# Generated by Django 2.1.1 on 2019-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='memory',
            field=models.PositiveIntegerField(verbose_name='Память (Гб)'),
        ),
        migrations.AlterField(
            model_name='samsung',
            name='extra_memory',
            field=models.PositiveIntegerField(verbose_name='Карта памяти (Гб)'),
        ),
    ]
